### ISSUE TITLE
How to switch to Japanese rules in gogui-twogtp?

### ISSUE THREAD

**Issue by Nyquixt** [Remi-Coulom/gogui#22]
I seems like the default rules for gogui-twogtp is Chinese. Is there a way to switch to Japanese? Thanks!

**Comment by Remi-Coulom** [comment]
gogui-twogtp asks the programs for their results. So you have to configure the gtp programs to use Japanese rules in order to score the games with Japanese rules. There is no standard gtp command to choose rules, so this option cannot be managed at the level of gogui-twogtp. For instance gnugo can be invoked with either the "--japanese-rules" or "--chinese-rules" option. Not all programs can handle Japanese rules.
